addons:
  code_climate:
    repo_token:
      secure: "b7R+UxhSZuIxFtpjsIm5Grya53+Hlku/unzzRxUs3MbwXUjPvJgguoP5lUYOYrfU6/JNq/7JyZfdYaxCCffYoyJJffPwjIUDVgJeaGKAVRrVsYXYvFQkv2pPzLpgnJjMhO+v3whkKfsAg39ovRSc+5/DpMwKE+u9qyRh6BYOngrkajMovxNndT1py0l2rWV+aWQjfNWUX2tD56aNvc2uc236jIwi1HUoAiAFXh91GHWL7AMDgwH5Ylv5OPUIvdi/qvXuFKtpDdQNRZLzvsuniWdXjpOwYnRbIBmhujwhG2qPbIYVl1SgwcJyZjWdI0ux2L0G6BE0BQs6so0+skNCSk4pSbsCeyqIoPn+UEN8ZkFBV0uyE4vIqwc88KMbMeQ7n+q7/pnFUYaMRyrj10kvWhsJQsAg9qKhQn21ftjj6HGhkRrHkUoXmOnrKpIH/J8+OsdEt72kYdEGpPDbaZPDIXh6mf3Mq2E7713bMKIDmjGsEdruCSr/NtD40JNG8QPhVCJGG7sGAiHJGzui7Y84uIu6k/WGjNBdoxWdT23yVmmnAHa+kT2GvTs8USqMKsT+GETVi0bMIaESQX7FoYNKS48p7vZcukDkvQLLejwjaQ7oMSxJNkfip4HIK0rGbQs3OUDm2hbA2uDcOZ+6QcLHX977LQr21749KpttAQPmUTg="
language: node_js
node_js:
- '6'
- '7'
- lts/*
sudo: false
cache:
  directories:
  - node_modules
before_script:
- npm install -g codeclimate-test-reporter
script:
- npm run eslint
- npm run nyc
after_script:
- codeclimate-test-reporter < ./coverage/lcov.info